import type { UserProfile, EventScope, ConnectionCard, GenesisEventItem, GenesisNotification } from '../types';

export const initialActiveUser: UserProfile = {
  id: 'user_gen_99182',
  fullName: 'Alex Vance',
  email: 'alex.vance@genesis.dev',
  phone: '+1 (555) 234-8901',
  avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=400&q=80',
  roleTitle: 'RAG Systems & Full-Stack Architect',
  coreTechStack: ['TypeScript', 'Python', 'React', 'Solana', 'PyTorch', 'Rust'],
  bio: 'Building autonomous AI agent frameworks & high-frequency developer platforms. 5x Hackathon winner.',
  pitch: 'Building a decentralized memory indexing agent for hackathon builders. Looking for Rust & Frontend devs!',
  socialLinks: {
    github: 'https://github.com/alexvance-dev',
    linkedin: 'https://linkedin.com/in/alexvance-dev',
    twitter: 'https://x.com/alexvance_dev',
    discord: 'alexvance#8892',
    portfolio: 'https://alexvance.dev',
    instagram: 'https://instagram.com/alexvance.builds',
  },
  socialVisibility: {
    github: true,
    linkedin: true,
    twitter: true,
    discord: false,
    portfolio: true,
    instagram: false,
  },
  badges: [
    {
      id: 'badge_1',
      name: 'Genesis Hacker Prime',
      icon: 'Zap',
      description: 'Attended 5+ Genesis Eco-Hackathons',
      unlockedAt: '2026-06-15',
    },
    {
      id: 'badge_2',
      name: 'Master Networker',
      icon: 'Users',
      description: 'Exchanged 50+ mutual cryptographic badges',
      unlockedAt: '2026-07-20',
    },
    {
      id: 'badge_3',
      name: 'AI Innovator',
      icon: 'Cpu',
      description: 'Built & submitted top-rated AI/ML project',
      unlockedAt: '2026-07-28',
    },
  ],
  totalConnections: 24,
};

export const currentEventScope: EventScope = {
  id: 'event_genesis_hacks_2026',
  name: 'Genesis Hacks Global 2026',
  location: 'Tech Hub Arena, Innovation Park',
  date: 'August 2–4, 2026',
  isCurrent: true,
};

export const initialConnections: ConnectionCard[] = [
  {
    id: 'conn_1',
    userId: 'user_sara_3312',
    fullName: 'Sarah Chen',
    roleTitle: 'Senior Rust & Smart Contract Dev',
    avatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=400&q=80',
    pitch: 'Building cross-chain ZK verification rollups. Need UI/UX lead.',
    eventId: 'event_genesis_hacks_2026',
    eventName: 'Genesis Hacks Global 2026',
    timestamp: '2026-08-02T19:30:00Z',
    tags: ['#Rust', '#Solana', '#ZeroKnowledge', '#FoundingPartner'],
    privateNote: 'Met near Main Stage after opening keynote. Interested in co-founding ZK infrastructure project. Follow up on Tuesday via Telegram.',
    socialLinks: {
      github: 'https://github.com/sarahchen-zk',
      linkedin: 'https://linkedin.com/in/sarahchen-rust',
      twitter: 'https://x.com/sarah_zk_rust',
    },
  },
  {
    id: 'conn_2',
    userId: 'user_marcus_991',
    fullName: 'Marcus Brody',
    roleTitle: 'AI Lead & Fine-Tuning Specialist',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=400&q=80',
    pitch: 'Fine-tuning Llama-3 70B models for local browser code synthesis.',
    eventId: 'event_genesis_hacks_2026',
    eventName: 'Genesis Hacks Global 2026',
    timestamp: '2026-08-02T20:15:00Z',
    tags: ['#AI/ML', '#PyTorch', '#LLMs', '#PotentialTeammate'],
    privateNote: 'Demonstrated high-speed inference pipeline running locally on RTX 4090. Wants to integrate with our Loopin backend!',
    socialLinks: {
      github: 'https://github.com/marcusbrody-ai',
      twitter: 'https://x.com/brody_llm',
      portfolio: 'https://brody.ai',
    },
  },
  {
    id: 'conn_3',
    userId: 'user_elena_442',
    fullName: 'Elena Rostova',
    roleTitle: 'Lead Product Designer & Design Engineer',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=400&q=80',
    pitch: 'Crafting spatial 3D glassmorphism UIs for Web3 & AI tooling.',
    eventId: 'event_genesis_summer_2026',
    eventName: 'Genesis Summer Meetup 2026',
    timestamp: '2026-07-28T18:00:00Z',
    tags: ['#UI/UX', '#Figma', '#ThreeJS', '#DesignSystems'],
    privateNote: 'Met at Genesis Summer Meetup. Created the visual identity for 3 winning hackathon teams.',
    socialLinks: {
      linkedin: 'https://linkedin.com/in/elena-rostova-design',
      portfolio: 'https://rostova.design',
    },
  },
  {
    id: 'conn_4',
    userId: 'user_devon_778',
    fullName: 'Devon Miles',
    roleTitle: 'DevOps & Distributed Systems Architect',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=400&q=80',
    pitch: 'Scaling Kubernetes clusters & Cloudflare Workers for sub-10ms APIs.',
    eventId: 'event_genesis_hacks_2026',
    eventName: 'Genesis Hacks Global 2026',
    timestamp: '2026-08-02T21:00:00Z',
    tags: ['#DevOps', '#Kubernetes', '#Go', '#Infrastructure'],
    privateNote: 'Ex-Cloudflare engineer. Offered to help set up our Redis caching & Rate Limiting infrastructure.',
    socialLinks: {
      github: 'https://github.com/devonmiles-k8s',
      linkedin: 'https://linkedin.com/in/devonmiles',
    },
  },
];

export const initialGenesisEvents: GenesisEventItem[] = [
  {
    id: 'event_genesis_hacks_2026',
    title: 'Genesis Hacks Global 2026',
    tagline: 'The Flagship 48-Hour Global Builder Odyssey & $100K Prize Pool',
    category: 'hackathon',
    date: 'August 2–4, 2026',
    location: 'Tech Hub Arena & Global Virtual Stream',
    participantsCount: 1250,
    imageUrl: 'https://images.unsplash.com/photo-1515187029135-18ee286d815b?auto=format&fit=crop&w=800&q=80',
    status: 'live',
    registrationUrl: 'https://genesis.dev/hacks-2026',
    agenda: [
      'Day 1 - 09:00 AM: Keynote & Team Matching',
      'Day 1 - 12:00 PM: Hacking Begins & QR Badges Active',
      'Day 2 - 03:00 PM: Mentor Office Hours & Pitch Workshop',
      'Day 3 - 12:00 PM: Project Submissions Cutoff',
      'Day 3 - 04:00 PM: Top 10 Live Demos & Award Ceremony',
    ],
  },
  {
    id: 'event_ai_agent_summit',
    title: 'Genesis Autonomous Agent Summit',
    tagline: 'Deep Dive into Multi-Agent Orchestration & On-Chain AI',
    category: 'workshop',
    date: 'August 15, 2026',
    location: 'San Francisco & Online',
    participantsCount: 450,
    imageUrl: 'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?auto=format&fit=crop&w=800&q=80',
    status: 'upcoming',
    registrationUrl: 'https://genesis.dev/agent-summit',
    agenda: [
      '10:00 AM: Keynote by Genesis AI Research Lead',
      '11:30 AM: Building RAG Chains with Local Vector DBs',
      '02:00 PM: Live Code-Along & Builder Networking',
    ],
  },
  {
    id: 'event_genesis_founder_meetup',
    title: 'Genesis Founders & Angels Night',
    tagline: 'Intimate Networking for Hackathon Alumni & Seed Investors',
    category: 'meetup',
    date: 'August 22, 2026',
    location: 'Rooftop Lounge, Palo Alto',
    participantsCount: 180,
    imageUrl: 'https://images.unsplash.com/photo-1511578314322-379afb476865?auto=format&fit=crop&w=800&q=80',
    status: 'upcoming',
    registrationUrl: 'https://genesis.dev/founders-night',
    agenda: [
      '06:30 PM: Welcome Cocktail & QR Loopin Scanning',
      '07:30 PM: 3-Minute Alumni Pitch Showcase',
      '08:30 PM: Investor Speed Dating',
    ],
  },
];

export const initialNotifications: GenesisNotification[] = [
  {
    id: 'notif_1',
    title: '⚡ QR Badge Active for Genesis Hacks',
    message: 'Your cryptographic QR badge is now active. Scan fellow builders to exchange details instantly!',
    timestamp: '10 mins ago',
    type: 'system',
    read: false,
  },
  {
    id: 'notif_2',
    title: '📢 Demo Day Pitch Submission Countdown',
    message: 'Submissions close in 14 hours! Ensure your Devpost & GitHub repo links are linked.',
    timestamp: '1 hour ago',
    type: 'deadline',
    read: false,
  },
  {
    id: 'notif_3',
    title: '🤝 Teammate Match Found',
    message: 'Sarah Chen (#Rust Lead) viewed your single-line pitch and connected with you!',
    timestamp: '2 hours ago',
    type: 'match',
    read: true,
  },
  {
    id: 'notif_4',
    title: '🚀 Founder & Angels Night Registration Open',
    message: 'Genesis Hackers get priority RSVP for our Palo Alto Founders Night on Aug 22.',
    timestamp: '1 day ago',
    type: 'announcement',
    read: true,
  },
];
